name: "Build and maybe publish site"
on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  ema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build sources & site 🔧
        run: |
          nix build .#site -j 4
      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: result
